### ISSUE TITLE
Single Mastodon Instance

### ISSUE THREAD

**Issue by polkonic** [cinderella-project/iMast#179]
Hello, 

i would like to publish this as my mastodon app only.
can i set to only one mastodon server, if i can how ? 

thank you.

**Comment by rinsuki** [comment]
It's technically possible, but there are a variety of other issues involved.

This app is published under an open source license, but it should be impossible under Apple's terms to publish this app's UI to the App Store as a separate app as it is.

Also, since this app is released under the Apache License 2.0 license, **you can't release the app as an "iMast".** Please be careful.

Also, the push notification server for this app is a proprietary implementation and the source code has not been published. And the official push notification server is only available in the official build (due to Apple's restrictions). So, you need to read the source code and disable push notifications or reimplement the server.

Technically, it is possible to edit the `AddAccountIndexViewController.swift` so that it can only be used in certain instances.
